baseurl = "https://jonathanlloyd.github.io/blog"
languageCode = "en"
title = "Jonathan Lloyd | Blog"
theme = "hemingway"
copyright = "&copy; Jonathan Lloyd 2018"
disqusShortname = "shortname"
googleAnalytics = ""

[params]

[params.highlight]
style = "github"
languages = ["go", "dockerfile"]

[[params.social]]
url = "https://github.com/jonathanlloyd"
fa_icon = "fa-github"

[[params.social]]
url = "https://twitter.com/lloydjonathan"
fa_icon = "fa-twitter"

[[params.social]]
url = "/index.xml"
fa_icon = "fa-rss"
